### ISSUE TITLE
When the OpenWrt router does not rely on dnsmasq, how to use DNS to forward to https-dns-proxy?

### ISSUE THREAD

**Issue by openwrt-diy** [aarond10/https_dns_proxy#101]
@aarond10 

Compiling the OpenWrt system firmware does not integrate dnsmasq and dnsmasq-full function plug-ins. The terminal device uses rp-pppoe dial-up server + mwan3 load balancing + https-dns-proxy to access the Internet! At this time, the 127.0.0.1 port forwarding does not take effect. How do I set up DNS forwarding?

**Comment by aarond10** [comment]
There are two bits of software here:

1. You can run the https-dns-proxy software on your router if you can compile it and get it there somehow, or you can run it on another machine on your network with `-a 0.0.0.0` so that your openwrt router can access it.
2. If your openwrt device supports some alternative DNS forwarder software to dnsmasq, you'll have to configure that to forward DNS requests through the host/port of https-dns-proxy. 

If you get the binary to run on the same device, the IP will be the loopback address (127.0.0.1), port 5053. If not, use the IP of the machine on your network.
