### ISSUE TITLE
https-dns-proxy on OpenWrt needs to be restarted on WAN updates

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#152]
Hello @baranyaib90 @aarond10 ,

Could you please help me understand if the `https-dns-proxy` service restarts on OpenWrt can be avoided on WAN updates? I never experienced it myself, but quite a few users reported that `https-dns-proxy` service stops responding to requests (I've never received any logs of any kind for that) until it's restarted after the WAN update (like a public IP being changed).

I've added the trigger for the service to be restarted on WAN updates, but since it requires two restarts of dnsmasq (one on stop and one on start), it's an expensive operation.

I wonder if anything can be done about it, either using a specific config options or making changes in the init file? I'm hoping you could provide a suggestion based on your familiarity with the RFC, despite not using OpenWrt yourselves.

Thanks!

**Comment by baranyaib90** [comment]
Hi, I understand the isse, but quite hard to figure out some good solution.
I have something in my mind, but need someone who can test it in such conditions:
If I have the time, I can make a patch to call https_client_reset() after some signal (like: SIGUSR1) arrives.
I'm expecting that it will clear libcurl so the proxy can process requests afterwards.
I'm hoping, that the DNS poller can survive the WAN IP change.

PS: I have lately bought an ASUS RT-AX1800U router (which is exactly ASUS RT-AX53U just renamed) which is quite well supported by OpenWRT.
So I will play again with OpenWRT since my TP-Link TL-WR1043ND, but sadly I have fixed IP by ISP.

**Comment by stangri** [comment]
@baranyaib90 Thank you for your reply. I will try to kill the instances on restart (via https://github.com/stangri/source.openwrt.melmac.net/commit/48a0cb16847b869ecbb04c0a1516b32686b61a9f) and see if that helps for now.

**Comment by aarond10** [comment]
Sorry, I've been out of cell coverage for a few days. Is the issue IP
address changes not causing session expiration?
I really need to sort out a newer router. I'm running a custom ToT OpenWRT
at the moment and I don't seem to get WAN disconnects that often.

**Comment by stangri** [comment]
I'm going to close it as I think I have figured out the way to quickly kill and respawn procd processes on OpenWrt, so it's not an issue anymore.
