### ISSUE TITLE
setting GIT_VERSION for cmake options has no effect on version in the binary

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#173]
@aarond10 @baranyaib90 this issue has grown in importance since OpenWrt now mangles the PKG_RELEASE variable outside of the package's Makefile control for development branch, but not release branch.

I'm building the package not from git repo, but from the github archive and setting [GIT_VERSION in the OpenWrt makefile](https://github.com/stangri/source.openwrt.melmac.net/blob/211cda8961d8464da9ffc6056f88b017585706bd/https-dns-proxy/Makefile#L22), doesn't seem to affect anything so I ended up needing to create a [patch](https://github.com/stangri/source.openwrt.melmac.net/blob/211cda8961d8464da9ffc6056f88b017585706bd/https-dns-proxy/patches/020-src-options.c-add-version.patch) which I update based on version from the Makefile with my own automation.

I wonder if it's some logic in the [CMakeLists.txt](https://github.com/aarond10/https_dns_proxy/blob/8afbba71502ddd5aee91602318875a03e86dfc4e/CMakeLists.txt#L40-L64) that needs to be updated for the build process to pick up the value of GIT_VERSION when building from gzipped source rather than git checkout or if I'm doing something wrong, but if I could get rid of the patch and be able to set the version from the OpenWrt Makefile, it might make my life much easier maintaining the package for both development and release branches.

**Comment by stangri** [comment]
@aarond10 @baranyaib90 ping?

**Comment by baranyaib90** [comment]
Hi, I'm sorry, but I don't have time anymore to support the project (https://github.com/aarond10/https_dns_proxy/pull/154#issue-1513166264).
If I would send some improvements in the future, thats not because I'm fixing reported issues. It would be because I'm contributing the changes that I needed for myself.
I would apprechiate if you won't mention me in the future in issues. Else I would have to unsubscribe from notifications entirely.
Thank you for your understanding!

**Comment by aarond10** [comment]
Sorry, I've been quite busy lately. I will do my best to have a look at
this this week.

**Comment by stangri** [comment]
Sorry, don't have the time to dig up the commit, but either you or other contributors have addressed this, and setting SW_VERSION in CMAKE OPTIONS works!
