### ISSUE TITLE
Any chance to support OpenResolve by OpenDNS?

### ISSUE THREAD

**Issue by rampageX** [aarond10/https_dns_proxy#6]
Google is good, but we can try another way.

https://www.openresolve.com/

**Comment by aarond10** [comment]
Oh, I didn't know this existed! It wouldn't be too hard to add support for this, but it's more than just a few lines. The Google API requests/responses and this are completely different. I should probably look at making the query code a bit more modular first.

**Comment by aarond10** [comment]
It's been months since first posted and the landscape has changed a lot over the past few days. 

The [draft DoH RFC](https://datatracker.ietf.org/doc/draft-ietf-doh-dns-over-https/?include_text=1) doesn't expand any responses into JSON objects (so far). OpenResolve uses a different format to both dns.google.com and clourflare-dns.com. I'm not sure spreading myself too thin over these variants is going to be worth it. Instead, I think I'd rather remove the JSON code from this proejct and switch to [DNS-over-TLS](https://tools.ietf.org/html/rfc7858) if/when it's more widely supported.
