### ISSUE TITLE
Support more DoH servers

### ISSUE THREAD

**Issue by stangri** [aarond10/https_dns_proxy#69]
Hello Aaron,
There are DoH servers which currently do not seem to work with this proxy:

```
https://dns.adguard.com/dns-query?
https://dns-family.adguard.com/dns-query?
https://doh.cleanbrowsing.org/doh/security-filter/?ct&
https://doh.cleanbrowsing.org/doh/family-filter/?ct&
https://doh.cleanbrowsing.org/doh/adult-filter/?ct&
https://dns.digitale-gesellschaft.ch/dns-query?
https://odvr.nic.cz/doh?
https://dns.quad9.net:5053/dns-query?
https://dns9.quad9.net:5053/dns-query?
https://dns10.quad9.net:5053/dns-query?
https://dns11.quad9.net:5053/dns-query?
```
I'm not competent enough in the protocol/C code to figure out if support can be added easily.

Could you please advise if it's just the incorrect URL/missing parameters which are required to make it work or if you need to modify something in the sources to add the support for the above.

Thanks!

**Comment by aarond10** [comment]
Sorry. I missed this one earlier. Did you figure anything out? 

I haven't checked but I suspect the binary encoded query/response format may be required by some of these providers. The binary format is MUCH better than the JSON format (IMHO) because it makes the translation so much simpler (smaller, less bugs, full RR support). I haven't had a chance to update the code to support this yet, but I intend to eventually get around to that unless someone beats me to it. :)

**Comment by stangri** [comment]
I'm sure it's either the URL query or JSON differences. I couldn't figure out wherever DoH servers should expect a name parameter or something else and wherever their json reply can be properly parsed by the proxy.

**Comment by aarond10** [comment]
This should work now. Please reopen if you still find they don't work.
