### ISSUE TITLE
ECS not working

### ISSUE THREAD

**Issue by gayhub-dev** [aarond10/https_dns_proxy#76]
try -e option with different subnet,but not get localized results

**Comment by aarond10** [comment]
This option has been removed from the latest version as it had no effect. 

The ECS command-line flag was supported by Google in their JSON API but it was never well supported elsewhere and was necessary there because EDNS could not be expressed via the JSON API. Now that we're using the binary proptocol (RFC8484), you should look to configure that with a recursive DNS resolver. 

dnsmasq I believe supports this via the `--add-subnet` option.
