### ISSUE TITLE
强烈建议保留ECS DNS接口

### ISSUE THREAD

**Issue by 2427237507** [aarond10/https_dns_proxy#80]
至少在中国他非常有用

**Comment by aarond10** [comment]
This is a request to add back ECN support. 

To be clear, ECN support is not removed. It's just using the DNS protocol rather than the mechanism that Google supported in their JSON API. 

That said, I can see a good reason to want to use it and none of the other caching DNS resolvers really give much clear control over this field. RFC8484 doesn't provide any guidance either. I'll treat this as a feature request but can't provide any hard time lines.

**Comment by 2427237507** [comment]
Good！But how should I use ECS on Google DNS?
Following is my configuration file：
config https_dns_proxy
        option listen_addr '127.0.0.1'
        option listen_port '5353'
        option user 'nobody'
        option group 'nogroup'
        option subnet_addr ' xxx.xx.xx.xx/xx'(My City's IP)
        option proxy_server ''
        option url_prefix 'https://dns.google/resolve?'

**Comment by 2427237507** [comment]
And I want to pass ECS parameters using the specified IP
But I don't know how to do this.
